# Generated by Django 3.2.25 on 2024-03-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('advanced_search', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=3)),
                ('request_status', models.CharField(blank=True, max_length=10, null=True)),
                ('request_response', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
